version: "3.8"

services:

  postgres_db:
    image: postgres:16
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: movierama
    ports:
      - "5432:5432"
    networks:
      - deployment_default
    volumes:
      - postgres_data:/var/lib/postgresql/data

networks:
  deployment_default:
    driver: bridge

volumes:
  postgres_data:
