spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/movierama
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

  liquibase:
    enabled: false

server:
  port: 8080
