spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/movierama
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.xml

server:
  port: 8080
  servlet:
    context-path: /movierama

jwt:
  secret: test-secret-must-be-at-least-32-bytes-long!!
  expiration: 3600000

logging:
  level:
    root: info
